import { useState, useEffect } from "react";
import Head from "next/head";
import Navbar from "../components/Navbar";
import movie from "../api/movie";
import Container from "@material-ui/core/Container";
import Grid from "@material-ui/core/Grid";
import Poster from "../components/Poster";
import CircularProgress from "@material-ui/core/CircularProgress";

export default function Home() {
  const [movies, setMovies] = useState([]);
  const [search, setSearch] = useState("");
  const [isLoading, setIsLoading] = useState(true);
  const searchMovie = async (e) => {
    e.preventDefault();
    if(search){
      setIsLoading(true)
      const res = await movie.get(`/search/${search}`);
      if (res.status === 200) {
        setMovies(res.data);
        setIsLoading(false)
        
      } else {
        console.log(res);
      }
    }else{
      const res = await movie.get("/movies");
      setMovies(res.data);
    }
  };

  useEffect(() => {
    const fetchMovies = async () => {
      const res = await movie.get("/movies");
      setMovies(res.data);
      setIsLoading(false)
      console.log(res);
    };
    fetchMovies();
  }, []);
  return (
    <div>
      <Head>
        <title>Rent Movies</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar
        value={search}
        onChange={(e) => setSearch(e.target.value)}
        onSubmit={searchMovie}
      />
      <Container style={{ paddingBottom: "15rem" }}>
        {!isLoading ? (
          <>
            <h1 style={{ fontWeight: "300", marginTop: "2rem" }}>
              Rent Your Favorite <strong>Movies</strong>
            </h1>
            <div>
              <Grid container spacing={3}>
                {movies.map((movie) => (
                  <Grid item xs={6} sm={3} key={movie.id_film}>
                    <Poster
                      image={movie.poster}
                      title={movie.judul}
                      price={movie.harga}
                    />
                  </Grid>
                ))}
              </Grid>
            </div>
          </>
        ) : (
          <div style={{width:"100%",height:"90vh",display:"flex",justifyContent:"center",alignItems:"center"}}>
          <CircularProgress style={{color:"#00D9C0"}}/>
          </div>
        )}
      </Container>
    </div>
  );
}
